apiVersion: v1
kind: Pod
metadata:
  name: demo-app-pod
  namespace: demo
  labels:
    app: demo-app
spec:
  containers:
  - name: my-app
    image: containersol/k8s-deployment-strategies
    ports:
    - name: http
      containerPort: 8080
    - name: probe
      containerPort: 8086
    env:
    - name: VERSION
      value: v1.0.0