apiVersion: v1
kind: Service
metadata:
  name: demo-app-rs
  namespace: demo
spec:
  selector:
    app: demoapp-rs
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo-app-rs
  namespace: demo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demoapp-rs
  template:
    metadata:
      labels:
        app: demoapp-rs
    spec:
      containers:
      - name: my-app
        image: manakmishra/k8sdemoapp:1.0
        ports:
        - name: http
          containerPort: 8080
        - name: probe
          containerPort: 8086
        env:
        - name: VERSION
          value: v1.0.0
