apiVersion: v1
kind: Service
metadata:
  name: demo-svc-np
  namespace: demo
spec:
  type: NodePort
  selector:
    app: demoapp
  ports:
  - protocol: TCP
    nodePort: 30080 #if you omit the 'nodePort' param then a random nodeport will be assigned
    port: 80
    targetPort: http
