apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: demo-app-ds
  namespace: demo
spec:
  selector:
    matchLabels:
      app: demoapp-ds
  template:
    metadata:
      labels:
        app: demoapp-ds
    spec:
      containers:
      - name: my-app
        image: manakmishra/k8sdemoapp:1.0
        ports:
        - name: http
          containerPort: 8080
        - name: probe
          containerPort: 8086
        env:
        - name: VERSION
          value: v1.0.0
