apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cronjob
  namespace: demo
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from Minikube
          restartPolicy: OnFailure